# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 355)
        MainWindow.setAccessibleName("")
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("background-color: #343436;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Botao_TesteTouch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Botao_TesteTouch.setGeometry(QtCore.QRect(20, 60, 111, 23))
        self.Botao_TesteTouch.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(87, 90, 97);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(113, 196, 223);\n"
"    color: rgb(34, 36, 43);\n"
"    border-radius:7\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"    background-color: rgb(62, 101, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10\n"
"\n"
"}")
        self.Botao_TesteTouch.setObjectName("Botao_TesteTouch")
        self.Botao_DiretorioTouch = QtWidgets.QToolButton(parent=self.centralwidget)
        self.Botao_DiretorioTouch.setGeometry(QtCore.QRect(470, 60, 25, 19))
        self.Botao_DiretorioTouch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Botao_DiretorioTouch.setObjectName("Botao_DiretorioTouch")
        self.Box_Valordeloop_Touch = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.Box_Valordeloop_Touch.setGeometry(QtCore.QRect(531, 60, 61, 23))
        self.Box_Valordeloop_Touch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Box_Valordeloop_Touch.setWrapping(True)
        self.Box_Valordeloop_Touch.setMinimum(1)
        self.Box_Valordeloop_Touch.setMaximum(1000000)
        self.Box_Valordeloop_Touch.setProperty("value", 1)
        self.Box_Valordeloop_Touch.setDisplayIntegerBase(10)
        self.Box_Valordeloop_Touch.setObjectName("Box_Valordeloop_Touch")
        self.Label_Diretorio_EXE_Touch = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_Diretorio_EXE_Touch.setGeometry(QtCore.QRect(170, 60, 291, 23))
        self.Label_Diretorio_EXE_Touch.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Label_Diretorio_EXE_Touch.setMouseTracking(False)
        self.Label_Diretorio_EXE_Touch.setTabletTracking(False)
        self.Label_Diretorio_EXE_Touch.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Label_Diretorio_EXE_Touch.setAcceptDrops(False)
        self.Label_Diretorio_EXE_Touch.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Label_Diretorio_EXE_Touch.setAutoFillBackground(False)
        self.Label_Diretorio_EXE_Touch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:5")
        self.Label_Diretorio_EXE_Touch.setText("")
        self.Label_Diretorio_EXE_Touch.setScaledContents(False)
        self.Label_Diretorio_EXE_Touch.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Label_Diretorio_EXE_Touch.setWordWrap(False)
        self.Label_Diretorio_EXE_Touch.setObjectName("Label_Diretorio_EXE_Touch")
        self.Label_Diretorio_EXE_Teclado = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_Diretorio_EXE_Teclado.setGeometry(QtCore.QRect(170, 120, 291, 23))
        self.Label_Diretorio_EXE_Teclado.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Label_Diretorio_EXE_Teclado.setMouseTracking(True)
        self.Label_Diretorio_EXE_Teclado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:5")
        self.Label_Diretorio_EXE_Teclado.setText("")
        self.Label_Diretorio_EXE_Teclado.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Label_Diretorio_EXE_Teclado.setObjectName("Label_Diretorio_EXE_Teclado")
        self.Box_Valordeloop_Teclado = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.Box_Valordeloop_Teclado.setGeometry(QtCore.QRect(531, 120, 61, 23))
        self.Box_Valordeloop_Teclado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Box_Valordeloop_Teclado.setWrapping(True)
        self.Box_Valordeloop_Teclado.setReadOnly(False)
        self.Box_Valordeloop_Teclado.setMinimum(1)
        self.Box_Valordeloop_Teclado.setMaximum(1000000)
        self.Box_Valordeloop_Teclado.setProperty("value", 1)
        self.Box_Valordeloop_Teclado.setObjectName("Box_Valordeloop_Teclado")
        self.Botao_TesteTeclado = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Botao_TesteTeclado.setGeometry(QtCore.QRect(20, 120, 111, 23))
        self.Botao_TesteTeclado.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(87, 90, 97);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(113, 196, 223);\n"
"    color: rgb(34, 36, 43);\n"
"    border-radius:7\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"    background-color: rgb(62, 101, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10\n"
"\n"
"}")
        self.Botao_TesteTeclado.setObjectName("Botao_TesteTeclado")
        self.Botao_DiretorioTeclado = QtWidgets.QToolButton(parent=self.centralwidget)
        self.Botao_DiretorioTeclado.setGeometry(QtCore.QRect(470, 120, 25, 19))
        self.Botao_DiretorioTeclado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Botao_DiretorioTeclado.setObjectName("Botao_DiretorioTeclado")
        self.Texto_Loop = QtWidgets.QLabel(parent=self.centralwidget)
        self.Texto_Loop.setGeometry(QtCore.QRect(547, 40, 47, 13))
        self.Texto_Loop.setStyleSheet("color: rgb(255, 255, 255);")
        self.Texto_Loop.setObjectName("Texto_Loop")
        self.Botao_reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Botao_reset.setGeometry(QtCore.QRect(20, 14, 75, 23))
        self.Botao_reset.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: #de0341;\n"
"    border-radius: 10;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(113, 196, 223);\n"
"    color: rgb(34, 36, 43);\n"
"    border-radius:7\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid #de0341;\n"
"    background-color:white;\n"
"    color: #de0341;\n"
"    border-radius:10\n"
"}")
        self.Botao_reset.setObjectName("Botao_reset")
        self.Label_Diretorio_Salvamento = QtWidgets.QLabel(parent=self.centralwidget)
        self.Label_Diretorio_Salvamento.setGeometry(QtCore.QRect(230, 320, 291, 23))
        self.Label_Diretorio_Salvamento.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.Label_Diretorio_Salvamento.setMouseTracking(False)
        self.Label_Diretorio_Salvamento.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-radius:5")
        self.Label_Diretorio_Salvamento.setText("")
        self.Label_Diretorio_Salvamento.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Label_Diretorio_Salvamento.setIndent(0)
        self.Label_Diretorio_Salvamento.setObjectName("Label_Diretorio_Salvamento")
        self.Texto_Localdesalvamento = QtWidgets.QLabel(parent=self.centralwidget)
        self.Texto_Localdesalvamento.setGeometry(QtCore.QRect(30, 320, 191, 23))
        self.Texto_Localdesalvamento.setStyleSheet("color: rgb(255, 255, 255);")
        self.Texto_Localdesalvamento.setObjectName("Texto_Localdesalvamento")
        self.Botao_DiretorioSalvamento = QtWidgets.QToolButton(parent=self.centralwidget)
        self.Botao_DiretorioSalvamento.setGeometry(QtCore.QRect(530, 320, 25, 19))
        self.Botao_DiretorioSalvamento.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Botao_DiretorioSalvamento.setObjectName("Botao_DiretorioSalvamento")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rotina de Teste"))
        self.Botao_TesteTouch.setText(_translate("MainWindow", "Teste de Touch"))
        self.Botao_DiretorioTouch.setText(_translate("MainWindow", "..."))
        self.Botao_TesteTeclado.setText(_translate("MainWindow", "Teste de Teclado"))
        self.Botao_DiretorioTeclado.setText(_translate("MainWindow", "..."))
        self.Texto_Loop.setText(_translate("MainWindow", "Loop"))
        self.Botao_reset.setText(_translate("MainWindow", "Reset"))
        self.Texto_Localdesalvamento.setText(_translate("MainWindow", "Local de salvamento do relatório:"))
        self.Botao_DiretorioSalvamento.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
